### ISSUE TITLE
Collect and add collaborator summaries

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/editioncrafter#129]
For each featured project, add description - to be composed by projects or adapted from NSF grant proposal - to their featured pages. If there is a standalone site that integrates the dual-pane display, these should be linked too

**Comment by NickLaiacona** [comment]
I'll keep the latest version here until we are ready to put them all on the website:

Project Descriptions
====

Bow in the Cloud
--

intro:
An edition of the anti-slavery literary anthology of The Bow in the Cloud, edited by the British abolitionist Mary Anne Rawson. This 400-page anthology, published in 1834, featured a mix of professional and non-professional writers who worked for anti-slavery societies across Great Britain. It also has a massive manuscript archive of over 600 items which shows Rawson’s solicitation letters, the cover letters sent to Rawson by contributors, original submissions, and revised fair copies of those submissions edited by Rawson and her colleagues. The aspiration of this edition is to show the genesis of the anthology, but also to demonstrate the networks involved in the making of it.

link:
https://antislavery-anthologies.org/books/bow-in-the-cloud/index


Dyngley Family
---

intro:
Early modern English people were avid collectors of medieval manuscripts filled with centuries-old texts related to medicine, astrology, agriculture, or craft manufacture. Having tracked and compiled data on early modern reader marks in over 115 later medieval manuscripts, the project “Old Books, New Science” seeks to understand why early modern readers valued this medieval knowledge, how generations of readers engaged with these manuscripts over time, and what role these older books played in the development of the new science. The first stage of the project focuses on Trinity College Cambridge MS O.8.35, a later fifteenth-century guide to medical practice.

link:
https://github.com/cu-mkp/dyngleyfamily-editioncrafter-data


Interviste Pescatori
----

text:
Around 1641 Galileo Galilei’s beloved pupil, Benedetto Castelli (ca. 1577–1643), presented to the Venetian Senate his expert advice on the most pressing hydrogeological problems impacting the Lagoon of Venice. The text, entitled Considerazione intorno alla laguna di Venezia [Consideration on the Venetian Lagoon], was printed for the first time posthumously, in the 1660 edition of Castelli’s renowned work, Della misura dell’acque correnti [On the Measurement of Running Waters] (Bologna, 1660). It offered an unexpected (for the Venetians) diagnosis of the reasons for the reduction of the water depth of the lagoon and a controversial solution to the problem. A manuscript copy of his Consideration on the Venetian Lagoon, preserved in the State Archives of Venice, and is linked to the activities of the water officers who were in charge of controlling all activities concerning water. Castelli’s text is part of a documentation folder entitled “Scritture sulle condizioni e stato della Laguna” [Writings on the conditions and state of the Lagoon], which is preserved in the acts of the Savi ed esecutori alle acque, pezzo 123 [the water magistrate’s acts].

The research on these sources has been conducted at Ca' Foscari University of Venice, Italy, in the framework of the EarlyGeoPraxis EarlyGeoPraxis (FARE project funded by the Italian Ministry of University and Research, cod. R184WNSTWH).

link:


Native Bound Unbound
---

text:
Driven by a singular vision to recover the complex histories of Indigenous slavery across the Americas, we have organized into a collective of individuals made up of researchers, paleographers, translators, designers, and technical programmers. The work has also been or is anticipated to be supported by collaborations with repositories (archives, libraries, and museums), universities, genealogical and historical societies and organizations, such as StoryCorps. 

Thanks to the support of the Andrew W. Mellon Foundation, the team has created a framework that has evolved into both a database and repository of digital content organized around people, places, stories, and archives. We are inspired by a decolonial and restorative methodology, defined in greater detail below in our values and methods. Part of this work has involved the creation of processes to decipher this material through transcription, translation, and a formula to identify the interconnections between people, places and events, charting points of intersection within and across documents. 

Our vision for the project is that as it develops, the initiative will also serve as a platform for activating these collections. Inspiring new forms of creative expression and advancing new scholarship, the initiative will serve as a major source for educators, scholars, storytellers, and artists. Scroll down to read about our values, methodologies and to meet the team and our partners.


link:
nativeboundunbound.org

FR 640
---

text:
Sometime after 1579, an anonymous individual began recording many different processes and techniques we would now classify as belonging to the fine arts, crafts, and various technologies.

Over the course of an unknown span of time (probably until 1588), this person filled 170 folios (or 340 single pages) with closely-written text and some hand-drawn figures containing recipes, instructions, fragmentary notes, firsthand accounts of trials with many materials and techniques, and observations on myriad subjects, including drawing instruction, pigment application, dyeing, coloring of metal, wax, and wood, imitation gem production, making molds and metal casts, arms and armor, plant and tree cultivation, preservation of animals, plants, and foodstuffs, distillation of turpentine, and much else.

The resulting manuscript, now housed in the Bibliothèque nationale de France (BnF) as Ms. Fr. 640, has been preserved since the early seventeenth century in the binding of Philippe de Béthune, count of Selles and Charost, apparently the manuscript’s first owner. Entitled Choses diverses (diverse things) on its spine, it entered the King’s Library (the core of the later BnF) as part of the donation of the Béthune family’s library in 1662 by Philippe’s son, Hippolyte de Béthune. Ms. Fr. 640 is a unique record giving insight into many subjects, but is focused especially on processes and practices of making things from natural materials. Thus, it is an especially valuable source for the history of craft and material culture, and for the history of art and science in the late sixteenth and early seventeenth centuries. Many things about this manuscript are, however, extraordinarily intriguing and puzzling.

link:
https://edition640.makingandknowing.org/
