### ISSUE TITLE
Redirect from github.io to editioncrafter.org

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/editioncrafter#130]
As of today, [editioncrafter.org](https://editioncrafter.org/) seems to have multiple errors - maybe something is wrong in the redirection from https://cu-mkp.github.io/editioncrafter/?

![image](https://github.com/cu-mkp/editioncrafter/assets/14779727/c46eea29-d624-4ef8-99df-3eed8dafd85d)

**Comment by ajolipa** [comment]
In order to set up the GitHub Pages site to be served from editioncrafter.org, in the DNS settings for the domain the following records should be created:
- A CNAME record that points the www subdomain at `https://cu-mkp.github.io/`
- An ALIAS record that points the apex domain at `https://cu-mkp.github.io/`
Once these are set up then GitHub can be configured to use the custom domain for the Pages site.

**Comment by njr2128** [comment]
editioncrafter.org is registered at AWS Route 53 (not through Bluehost as we had thought). 

We were able to configure a CNAME record for www.editioncrafter.org pointing it to `cu-mkp.github.io`
We don't know how to create an ALIAS record that points editioncrafter.org to the `cu-mkp.github.io` domain. An ALIAS A record seems to only be able to point to an IP4 address. Can you provide more detailed info? Thank you!
