### ISSUE TITLE
Eliminate React warnings 

### ISSUE THREAD

**Issue by NickLaiacona** [cu-mkp/editioncrafter#21]
When EC component is mounted, a couple of warnings are displayed in the JS console related to componentWillMount and componentWillReceiveProps usage. Refactor code as necessary to eliminate these. This is related to repairing the XML mode button. See the ImageView for an example of how to potentially refactor this.

**Comment by camdendotlol** [comment]
It looks like there's one affected Edition Crafter component: `JumpToFolio`. The other warnings are coming from components within `react-router` and should be fixed by upgrading that package to the latest version.

I'll go ahead with the `react-router` upgrade first. Did I miss any components besides `JumpToFolio` that are affected?

**Comment by SteveMarvin** [comment]
Getting these whenever I load a page:


![Image](https://github.com/cu-mkp/editioncrafter/assets/18423533/3c77d8cb-b3d5-4fad-9376-4a82302d5f47)
